### ISSUE TITLE
Stuck on Downloading Tasks

### ISSUE THREAD

**Issue by drmikecrowe** [piejanssens/premiumizer#279]
Within the past 1-2d, I'm starting to simply see:

![image](https://user-images.githubusercontent.com/90312/103439449-12482000-4c0b-11eb-808e-bce0d2553a0c.png)

FWIW, I was also getting an `Uncaught TypeError: encodedPayload.split is not a function` in the browser console.  Upgrading to `3.0.3` of socket.io in `index.html` fixed that error, but still no luck showing the tasks

**Comment by xxcriticxx** [comment]
I have same problem on windows 10. Loading Download Tasks message and gear spins in loop.

**Comment by piejanssens** [comment]
I can't reproduce the issue. I just pushed a new commit updating the socketio lib to 3.0.4. Can you both test and please make sure to check while loading the page in the network panel of your browser dev tools that it's not using an old cached version of socketio.js.

**Comment by neox387** [comment]
Updated my installer to use python 3.8.7, do not use 3.9.x gevent had no wheel installer for it.

Reinstalled my premiumizer on windows and it's working fine so far.

Got a PR for some missing config setting to auto update depencies #280

**Comment by piejanssens** [comment]
@neox387 Thanks!

**Comment by xxcriticxx** [comment]
cc @piejanssens / @neox387 

Updated on win10 and service wont start again after the update. Cleared browser data. Service still wont start. Restarted service but service still wont start. Restart my pc but did not help. Removed whole application and installed it again. While in installation got the following error. 

![Capture](https://user-images.githubusercontent.com/15007183/103643894-72003d00-4f23-11eb-8707-a4ab8a3c5fce.PNG)

Press "OK"  couple times and error goes away. 

After installation it looks like application is working but I have message on top "Downloads are disabled" that wont go away. 

![Capture1](https://user-images.githubusercontent.com/15007183/103644053-b8ee3280-4f23-11eb-85bc-c3450d3df62a.PNG)

**Comment by neox387** [comment]
I do change the log on for the service and use the admin account, else network shares did not work in the past.

**Comment by xxcriticxx** [comment]
@neox387 if I understand correctly you want me to change from "Local System account" to "This account:"?

**Comment by neox387** [comment]
this is only needed for some permission erros on folders like if you use a network location

> 01-09 14:28:49: INFO : Creating Download Path at: \\10.0.0.2\video\tmp\tv
01-09 14:28:49: ERROR : Downloads disabled cannot Create download directory: \\10.0.0.2\video\tmp\tv --- error: [WinError 5] Access is denied: '\\\\10.0.0.2\\video\\'

**Comment by xxcriticxx** [comment]
@neox387 I don't use a network location. All my files are stored locally on a D: drive.
